pring:
  application:
    name: collector
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: false

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.kafka.serializer.AvroSerializer
    acks: "all"
    retries: 3
    max-in-flight-requests: 5
    enable-idempotence: true

topic:
  sensor-events: telemetry.sensors.v1
  hub-events: telemetry.hubs.v1

grpc:
  server:
    port: 59091