# Kafka producer
kafka.producer.bootstrap-servers=localhost:9092
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.AvroSerializer
kafka.producer.acks=all
kafka.producer.retries=3
kafka.producer.max-in-flight-requests=1
kafka.producer.enable-idempotence=true

# Kafka topics
topic.hub-events=telemetry.hubs.v1
topic.sensor-events=telemetry.sensors.v1

# Logging
logging.level.ru.yandex.practicum=TRACE