spring.application.name=aggregator

# Kafka config
kafka.consumer.bootstrap-servers=localhost:9092
kafka.consumer.group-id=aggregator-group
kafka.producer.bootstrap-servers=localhost:9092

kafka.topics.sensor-events=telemetry.sensors.v1
kafka.topics.snapshots=telemetry.snapshots.v1

logging.level.ru.yandex.practicum=DEBUG