spring:
  application:
    name: analyzer
  config:
    import: configserver:http://localhost:8080
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/sht-db
    username: main
    password: main

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/