spring:
  application:
    name: analyzer
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/sht-db
    username: main
    password: main
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092
  topics:
    hub-events: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 0